server:
  port: 8088

spring:
  profiles:
    active: dev

logging:
  level:
    root: info

sureness:
  container: servlet
  auths:
    - digest
    - basic
    - jwt
  jwt:
    secret: ?::4s9ssf2sf4sed45pf):RnLN7XNn4wARoQXizIv6MHUsIV+EFfiMw/x7R0ntu4aWr/CWuApcFajCyaFv0bwq2Eik0jdrKUtsA6bx3sDJeFV643R+YYzGMRIqcBIp6AKA98GM2RIqcBIp6-?::4390fsf4sdl6opf)4ZI:tdQMtcQQ14pkOAQdQ546
  annotation:
    enable: true
    scan-packages:
      - org.dromara.sureness.bootstrap.controller
  session:
    enable: true
  websocket:
    enable: true
